defmodule ProtectoraWeb.Components.Card do
  @moduledoc """
  A sample component generated by `mix surface.init`.
  """
  use Phoenix.LiveComponent
  use Phoenix.HTML

  @impl true
  def render(assigns) do
    ~H"""
    <div
      class={"card w-80 min-h-80 overflow-hidden shadow-lg mb-2 max-h-md max-w-md rounded-2xl"}
      id={@id}

    >
    <div class="header p-3 font-semibold text-xl text-teal-600 w-full bg-gray-200">
      </div>

      <div class="content  px-6 py-4 text-gray-700 text-base">
        <div class="name space-x-4">
          <strong>Nome:
          </strong>
         <%=@animal.nome%>
        </div>
        <div class="tipo space-x-1">
          <strong>Tipo:
          </strong>
           <%= @animal.tipo %>
        </div>
        <div class="tamano space-x-4">
          <strong>Tamaño:
          </strong>
           <%=@animal.tamano%>
        </div>
        <div class="imaxe mb-1 mt-4">
          <%= if length(@animal.imaxe_animal) > 0 do %>
              <img src={Enum.at(@animal.imaxe_animal, 0).path_imaxe}>
          <% else %>
            <div class="" />
          <% end %>
        </div>
        <div class="link text-blue-600">
          <%= live_redirect "Ensinar", to: ProtectoraWeb.Router.Helpers.animal_show_path(@socket, :show, @animal) %>
        </div>
        <div class="link text-blue-600">
          <%= live_patch "Editar", to: ProtectoraWeb.Router.Helpers.animal_index_path(@socket, :edit, @animal) %>
        </div>
        <div class="link text-blue-600">
          <%= link "Borrar", to: "#", phx_click: "delete", phx_value_id: @animal.id, data: [confirm: "Are you sure?"] %>
        </div>
      </div>
    </div>
    """
  end
end
