# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Elixir CI

on:
  push:
    branches:
    - main
    - feat/*
    - develop
    - fix/* 
    - refactor/*
    - feature/*
  
  pull_request:
    branches:
    - main
    - feat/*
    - develop
    - fix/* 
    - refactor/*
    - feature/*
    
permissions:
  contents: read

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-beam@988e02bfe678367a02564f65ca2e37726dc0268f
      with:
        elixir-version: '1.13.1' # Define the elixir version [required]
        otp-version: '24' # Define the OTP version [required]
      env:
        # See:
        # https://github.com/erlef/setup-beam/blob/master/src/setup-beam.js#L340
        ImageOS: ubuntu20 
          
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: mix test
      
  run_tests:
    runs-on: ubuntu-latest
    steps:
    # This is an action from github that checks out the code in the repo.
    - uses: actions/checkout@v2
    # Give it any name you like
    - name: "run dem tests"
      uses: Adzz/elixir_run_tests_action@v2.0.0
